# Basic
max_width = 100
# Imports
# nightly group_imports = "StdExternalCrate"
# nightly imports_granularity = "Module"
reorder_imports = true
# Comments
# nightly comment_width = 100
# nightly normalize_comments = true
# nightly wrap_comments = true
# Consistency
newline_style = "Unix"
