[workspace]
members = [
    "dsp-domain",
    "dsp-meta",
    "dsp-meta-cli",
    "dsp-meta-server"
]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1.68"
axum = "0.6.20" # web framework
axum-macros = "0.3.8"
clap = { version = "4.4.8", features = ["derive"] } # command-line parser
config = "0.13.1" # Layered configuration with strong support for 12-factor applications
dirs = "5.0.1" # provides platform-specific locations for storing user configuration
hcl-rs = "0.16.6" # HCL converter
indicatif = "0.17.0" # prograss bars and spinners
log = "0.4.20" # logging facade
once_cell = "1.18.0"
serde = {version = "1", features = ["derive"]}
serde_json = "1" # JSON serialization
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
tokio-test = "0.4.2"
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["trace"] }
hyper = "0.14.27"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-test = "0.2"
url = { version = "2", features = ["serde"] }
