[package]
about = "The DSP-Meta tooling transforms project's metadata provide in toml files to JSON and TTL."
authors = ["Swiss National Data and Service Center for the Humanities (DaSCH)"]
name = "dsp-meta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.68"
clap = { version = "4.3.8", features = ["derive"] } # command-line parser
config = "0.13.1" # Layered configuration with strong support for 12-factor applications
dirs = "5.0.1" # provides platform-specific locations for storing user configuration
indicatif = "0.17.0" # prograss bars and spinners
once_cell = "1.18.0"
tokio = { version = "1.28.2", features = ["rt", "macros", "rt-multi-thread"] }
tokio-test = "0.4.2"
serde = "1.0.164"
serde_json = "1.0.99"
toml = "0.7.1"
warp = "0.3.5"

