[package]
name = "dsp-meta"
version = "2.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/dasch-swiss/dsp-meta"
repository = "https://github.com/dasch-swiss/dsp-meta"
documentation = "https://github.com/dasch-swiss/dsp-meta"
readme = "README.md"
description = "DSP-META is a service that provides metadata for the DaSCH Service Platform (DSP)."
authors = ["DaSCH - Swiss National Data and Service Center for the Humanities"]

[dependencies]
anyhow = "1"
async-trait = "0.1.81"
axum = "0.7.2" # web framework
axum-macros = "0.4.0"
clap = { version = "4.5.16", features = ["derive"] } # command-line parser
config = "0.13.1" # Layered configuration with strong support for 12-factor applications
chrono = { version = "0.4.38", features = ["serde"] }
dirs = "5.0.1" # provides platform-specific locations for storing user configuration
http-body-util = "0.1.0"
indicatif = "0.17.0" # prograss bars and spinners
log = "0.4.22" # logging facade
once_cell = "1.19.0"
pid1 = "0.1.1"
serde = { version = "1", features = ["derive"] }
serde_with = "3.9.0"
serde_json = "1" # JSON serialization
nonempty = { version = "0.10.0", features = ["serialize"] }
valico = "4.0.0"
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
tokio-test = "0.4.2"
tower = "0.4.13"
tower-http = { version = "0.5.0", features = ["trace", "fs", "cors"] }
hyper = "1.4.1"
regex = "1.10.6"
thiserror = "1.0.56"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "fmt",
    "registry",
    "std",
    "env-filter",
    "json",
] }
tracing-test = "0.2"
url = { version = "2", features = ["serde"] }

[dev-dependencies]
assert_cmd = "2.0.16"
axum-test = "15.3.0"
fake = "2.9.2"

[[bin]]
name = "dsp-meta-server"
path = "src/main-server.rs"

[[bin]]
name = "dsp-meta-validator"
path = "src/main-validator.rs"