[workspace]
members = ["dsp-domain", "dsp-meta", "dsp-meta-cmd", "serde-rdf"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.package]
version = "2.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/dasch-swiss/dsp-meta"
repository = "https://github.com/dasch-swiss/dsp-meta"
documentation = "https://github.com/dasch-swiss/dsp-meta"
readme = "README.md"
description = "The DSP Metadata Command Line Tool providing transformation, validation and serving of research project's metadata."
authors = ["DaSCH - Swiss National Data and Service Center for the Humanities"]

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1.81"
axum = "0.7.2" # web framework
axum-macros = "0.4.0"
clap = { version = "4.5.15", features = ["derive"] } # command-line parser
config = "0.13.1" # Layered configuration with strong support for 12-factor applications
chrono = { version = "0.4.38", features = ["serde"] }
dirs = "5.0.1" # provides platform-specific locations for storing user configuration
hcl-rs = "0.16.7" # HCL converter
http-body-util = "0.1.0"
indicatif = "0.17.0" # prograss bars and spinners
log = "0.4.22" # logging facade
once_cell = "1.19.0"
pid1 = "0.1.1"
serde = { version = "1", features = ["derive"] }
serde_with = "3.9.0"
serde_json = "1" # JSON serialization
serde_yaml = "0.9"
nonempty = { version = "0.10.0", features = ["serialize"] }
valico = "4.0.0"
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
tokio-test = "0.4.2"
tower = "0.4.13"
tower-http = { version = "0.5.0", features = ["trace", "fs", "cors"] }
hyper = "1.4.1"
regex = "1.5.4"
thiserror = "1.0.56"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "fmt",
    "registry",
    "std",
    "env-filter",
    "json",
] }
tracing-test = "0.2"
url = { version = "2", features = ["serde"] }
toml = "0.8.15"
