name: docker-build

on:
  pull_request:

jobs:

  # Docker build for amd64
  docker-build-amd64:
    runs-on: buildjet-4vcpu-ubuntu-2204
    concurrency:
      group: ${{ github.ref }}-docker-build-amd64
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # gets additionally all tags which we need
      - uses: extractions/setup-just@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: just docker-build-amd64

  # Docker build for arm64
  docker-build-arm64:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    concurrency:
      group: ${{ github.ref }}-docker-build-arm64
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # gets additionally all tags which we need
      - uses: extractions/setup-just@v2
      - uses: docker/setup-buildx-action@v3
      - run: just docker-build-arm64
