name: CI

on:
  pull_request:

jobs:

  # Docker build for amd64
  build_amd64:
    name: amd64
    runs-on: buildjet-4vcpu-ubuntu-2204
    concurrency:
      group: ${{ github.ref }}-docker-build-amd64
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # gets additionally all tags which we need
      - uses: extractions/setup-just@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: just docker-build-amd64

  # Docker build for arm64
  build_arm64:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    concurrency:
      group: ${{ github.ref }}-docker-build-arm64
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # gets additionally all tags which we need
      - uses: extractions/setup-just@v1
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: just docker-build-arm64
